[package]
edition = "2021"
name = "fpt"
version = "0.1.0"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.7"
clap = { version = "4.4.6", features = ["derive"] }
hlua = {version = "0.4.1", optional = true}
rustyline = {version = "12", optional = true}

[dev-dependencies]
rstest = "0.18"

[[bin]]
name = "main"

[[bin]]
name = "gui"

[[bin]]
name = "debug"
required-features = ["hlua", "rustyline"]

[[bin]]
name = "objdump"
