#[derive(Clone, PartialEq, Debug)]
pub struct Instruction {
    pub opcode: u16,
    pub mnemonic: String,
    pub size: u8,
    pub cycles: u8,
    pub cycles_not_taken: u8,
    pub kind: InstructionKind,
}

#[derive(Clone, PartialEq, Debug)]
pub enum InstructionKind {
    Control,
    Jump,
    LSM8Bit, // Load/store/move
    LSM16Bit,
    AL8Bit, // Arithmetic/Logic
    AL16Bit,
    RSB8Bit, // Rotate/Shift and Bit
}

impl Instruction {
    // Arguments in the same order as https://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html
    fn new(
        opcode: u16,
        mnemonic: &str,
        size: u8,
        cycles: u8,
        cycles_not_taken: u8,
        kind: InstructionKind,
    ) -> Self {
        let mnemonic = mnemonic.to_string();
        Self {
            opcode,
            mnemonic,
            size,
            cycles,
            cycles_not_taken,
            kind,
        }
    }
}

pub fn instructions() -> Vec<Instruction> {
    vec![
        Instruction::new(0x00, "NOP", 1, 4, 0, InstructionKind::Control),
        Instruction::new(0x01, "LD BC,d16", 3, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0x02, "LD (BC),A", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x03, "INC BC", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x04, "INC B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x05, "DEC B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x06, "LD B,d8", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x07, "RLCA", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x08, "LD (a16),SP", 3, 20, 0, InstructionKind::LSM16Bit),
        Instruction::new(0x09, "ADD HL,BC", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x0A, "LD A,(BC)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x0B, "DEC BC", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x0C, "INC C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x0D, "DEC C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x0E, "LD C,d8", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x0F, "RRCA", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x10, "STOP 0", 2, 4, 0, InstructionKind::Control),
        Instruction::new(0x11, "LD DE,d16", 3, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0x12, "LD (DE),A", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x13, "INC DE", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x14, "INC D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x15, "DEC D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x16, "LD D,d8", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x17, "RLA", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x18, "JR r8", 2, 12, 0, InstructionKind::Jump),
        Instruction::new(0x19, "ADD HL,DE", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x1A, "LD A,(DE)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x1B, "DEC DE", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x1C, "INC E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x1D, "DEC E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x1E, "LD E,d8", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x1F, "RRA", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x20, "JR NZ,r8", 2, 12, 8, InstructionKind::Jump),
        Instruction::new(0x21, "LD HL,d16", 3, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0x22, "LD (HL+),A", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x23, "INC HL", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x24, "INC H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x25, "DEC H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x26, "LD H,d8", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x27, "DAA", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x28, "JR Z,r8", 2, 12, 8, InstructionKind::Jump),
        Instruction::new(0x29, "ADD HL,HL", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x2A, "LD A,(HL+)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x2B, "DEC HL", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x2C, "INC L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x2D, "DEC L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x2E, "LD L,d8", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x2F, "CPL", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x30, "JR NC,r8", 2, 12, 8, InstructionKind::Jump),
        Instruction::new(0x31, "LD SP,d16", 3, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0x32, "LD (HL-),A", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x33, "INC SP", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x34, "INC (HL)", 1, 12, 0, InstructionKind::AL8Bit),
        Instruction::new(0x35, "DEC (HL)", 1, 12, 0, InstructionKind::AL8Bit),
        Instruction::new(0x36, "LD (HL),d8", 2, 12, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x37, "SCF", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x38, "JR C,r8", 2, 12, 8, InstructionKind::Jump),
        Instruction::new(0x39, "ADD HL,SP", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x3A, "LD A,(HL-)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x3B, "DEC SP", 1, 8, 0, InstructionKind::AL16Bit),
        Instruction::new(0x3C, "INC A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x3D, "DEC A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x3E, "LD A,d8", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x3F, "CCF", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x40, "LD B,B", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x41, "LD B,C", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x42, "LD B,D", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x43, "LD B,E", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x44, "LD B,H", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x45, "LD B,L", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x46, "LD B,(HL)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x47, "LD B,A", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x48, "LD C,B", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x49, "LD C,C", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x4A, "LD C,D", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x4B, "LD C,E", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x4C, "LD C,H", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x4D, "LD C,L", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x4E, "LD C,(HL)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x4F, "LD C,A", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x50, "LD D,B", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x51, "LD D,C", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x52, "LD D,D", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x53, "LD D,E", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x54, "LD D,H", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x55, "LD D,L", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x56, "LD D,(HL)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x57, "LD D,A", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x58, "LD E,B", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x59, "LD E,C", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x5A, "LD E,D", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x5B, "LD E,E", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x5C, "LD E,H", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x5D, "LD E,L", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x5E, "LD E,(HL)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x5F, "LD E,A", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x60, "LD H,B", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x61, "LD H,C", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x62, "LD H,D", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x63, "LD H,E", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x64, "LD H,H", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x65, "LD H,L", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x66, "LD H,(HL)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x67, "LD H,A", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x68, "LD L,B", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x69, "LD L,C", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x6A, "LD L,D", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x6B, "LD L,E", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x6C, "LD L,H", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x6D, "LD L,L", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x6E, "LD L,(HL)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x6F, "LD L,A", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x70, "LD (HL),B", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x71, "LD (HL),C", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x72, "LD (HL),D", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x73, "LD (HL),E", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x74, "LD (HL),H", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x75, "LD (HL),L", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x76, "HALT", 1, 4, 0, InstructionKind::Control),
        Instruction::new(0x77, "LD (HL),A", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x78, "LD A,B", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x79, "LD A,C", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x7A, "LD A,D", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x7B, "LD A,E", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x7C, "LD A,H", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x7D, "LD A,L", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x7E, "LD A,(HL)", 1, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x7F, "LD A,A", 1, 4, 0, InstructionKind::LSM8Bit),
        Instruction::new(0x80, "ADD A,B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x81, "ADD A,C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x82, "ADD A,D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x83, "ADD A,E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x84, "ADD A,H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x85, "ADD A,L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x86, "ADD A,(HL)", 1, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0x87, "ADD A,A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x88, "ADC A,B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x89, "ADC A,C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x8A, "ADC A,D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x8B, "ADC A,E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x8C, "ADC A,H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x8D, "ADC A,L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x8E, "ADC A,(HL)", 1, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0x8F, "ADC A,A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x90, "SUB B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x91, "SUB C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x92, "SUB D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x93, "SUB E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x94, "SUB H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x95, "SUB L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x96, "SUB (HL)", 1, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0x97, "SUB A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x98, "SBC A,B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x99, "SBC A,C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x9A, "SBC A,D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x9B, "SBC A,E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x9C, "SBC A,H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x9D, "SBC A,L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0x9E, "SBC A,(HL)", 1, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0x9F, "SBC A,A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA0, "AND B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA1, "AND C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA2, "AND D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA3, "AND E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA4, "AND H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA5, "AND L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA6, "AND (HL)", 1, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA7, "AND A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA8, "XOR B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xA9, "XOR C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xAA, "XOR D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xAB, "XOR E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xAC, "XOR H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xAD, "XOR L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xAE, "XOR (HL)", 1, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xAF, "XOR A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB0, "OR B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB1, "OR C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB2, "OR D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB3, "OR E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB4, "OR H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB5, "OR L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB6, "OR (HL)", 1, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB7, "OR A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB8, "CP B", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xB9, "CP C", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xBA, "CP D", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xBB, "CP E", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xBC, "CP H", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xBD, "CP L", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xBE, "CP (HL)", 1, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xBF, "CP A", 1, 4, 0, InstructionKind::AL8Bit),
        Instruction::new(0xC0, "RET NZ", 1, 20, 8, InstructionKind::Jump),
        Instruction::new(0xC1, "POP BC", 1, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xC2, "JP NZ,a16", 3, 16, 12, InstructionKind::Jump),
        Instruction::new(0xC3, "JP a16", 3, 16, 0, InstructionKind::Jump),
        Instruction::new(0xC4, "CALL NZ,a16", 3, 24, 12, InstructionKind::Jump),
        Instruction::new(0xC5, "PUSH BC", 1, 16, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xC6, "ADD A,d8", 2, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xC7, "RST 00H", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xC8, "RET Z", 1, 20, 8, InstructionKind::Jump),
        Instruction::new(0xC9, "RET", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xCA, "JP Z,a16", 3, 16, 12, InstructionKind::Jump),
        Instruction::new(0xCB, "PREFIX CB", 1, 4, 0, InstructionKind::Control),
        Instruction::new(0xCC, "CALL Z,a16", 3, 24, 12, InstructionKind::Jump),
        Instruction::new(0xCD, "CALL a16", 3, 24, 0, InstructionKind::Jump),
        Instruction::new(0xCE, "ADC A,d8", 2, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xCF, "RST 08H", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xD0, "RET NC", 1, 20, 8, InstructionKind::Jump),
        Instruction::new(0xD1, "POP DE", 1, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xD2, "JP NC,a16", 3, 16, 12, InstructionKind::Jump),
        Instruction::new(0xD3, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xD4, "CALL NC,a16", 3, 24, 12, InstructionKind::Jump),
        Instruction::new(0xD5, "PUSH DE", 1, 16, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xD6, "SUB d8", 2, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xD7, "RST 10H", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xD8, "RET C", 1, 20, 8, InstructionKind::Jump),
        Instruction::new(0xD9, "RETI", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xDA, "JP C,a16", 3, 16, 12, InstructionKind::Jump),
        Instruction::new(0xDB, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xDC, "CALL C,a16", 3, 24, 12, InstructionKind::Jump),
        Instruction::new(0xDD, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xDE, "SBC A,d8", 2, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xDF, "RST 18H", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xE0, "LDH (a8),A", 2, 12, 0, InstructionKind::LSM8Bit),
        Instruction::new(0xE1, "POP HL", 1, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xE2, "LD (C),A", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0xE3, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xE4, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xE5, "PUSH HL", 1, 16, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xE6, "AND d8", 2, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xE7, "RST 20H", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xE8, "ADD SP,r8", 2, 16, 0, InstructionKind::AL16Bit),
        Instruction::new(0xE9, "JP (HL)", 1, 4, 0, InstructionKind::Jump),
        Instruction::new(0xEA, "LD (a16),A", 3, 16, 0, InstructionKind::LSM8Bit),
        Instruction::new(0xEB, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xEC, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xED, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xEE, "XOR d8", 2, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xEF, "RST 28H", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xF0, "LDH A,(a8)", 2, 12, 0, InstructionKind::LSM8Bit),
        Instruction::new(0xF1, "POP AF", 1, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xF2, "LD A,(C)", 2, 8, 0, InstructionKind::LSM8Bit),
        Instruction::new(0xF3, "DI", 1, 4, 0, InstructionKind::Control),
        Instruction::new(0xF4, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xF5, "PUSH AF", 1, 16, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xF6, "OR d8", 2, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xF7, "RST 30H", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0xF8, "LD HL,SP+r8", 2, 12, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xF9, "LD SP,HL", 1, 8, 0, InstructionKind::LSM16Bit),
        Instruction::new(0xFA, "LD A,(a16)", 3, 16, 0, InstructionKind::LSM8Bit),
        Instruction::new(0xFB, "EI", 1, 4, 0, InstructionKind::Control),
        Instruction::new(0xFC, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xFD, "NOTHING", 0, 0, 0, InstructionKind::Control),
        Instruction::new(0xFE, "CP d8", 2, 8, 0, InstructionKind::AL8Bit),
        Instruction::new(0xFF, "RST 38H", 1, 16, 0, InstructionKind::Jump),
        Instruction::new(0x100, "RLC B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x101, "RLC C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x102, "RLC D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x103, "RLC E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x104, "RLC H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x105, "RLC L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x106, "RLC (HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x107, "RLC A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x108, "RRC B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x109, "RRC C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x10A, "RRC D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x10B, "RRC E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x10C, "RRC H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x10D, "RRC L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x10E, "RRC (HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x10F, "RRC A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x110, "RL B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x111, "RL C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x112, "RL D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x113, "RL E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x114, "RL H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x115, "RL L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x116, "RL (HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x117, "RL A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x118, "RR B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x119, "RR C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x11A, "RR D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x11B, "RR E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x11C, "RR H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x11D, "RR L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x11E, "RR (HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x11F, "RR A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x120, "SLA B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x121, "SLA C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x122, "SLA D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x123, "SLA E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x124, "SLA H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x125, "SLA L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x126, "SLA (HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x127, "SLA A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x128, "SRA B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x129, "SRA C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x12A, "SRA D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x12B, "SRA E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x12C, "SRA H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x12D, "SRA L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x12E, "SRA (HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x12F, "SRA A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x130, "SWAP B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x131, "SWAP C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x132, "SWAP D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x133, "SWAP E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x134, "SWAP H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x135, "SWAP L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x136, "SWAP (HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x137, "SWAP A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x138, "SRL B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x139, "SRL C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x13A, "SRL D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x13B, "SRL E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x13C, "SRL H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x13D, "SRL L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x13E, "SRL (HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x13F, "SRL A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x140, "BIT 0,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x141, "BIT 0,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x142, "BIT 0,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x143, "BIT 0,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x144, "BIT 0,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x145, "BIT 0,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x146, "BIT 0,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x147, "BIT 0,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x148, "BIT 1,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x149, "BIT 1,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x14A, "BIT 1,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x14B, "BIT 1,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x14C, "BIT 1,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x14D, "BIT 1,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x14E, "BIT 1,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x14F, "BIT 1,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x150, "BIT 2,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x151, "BIT 2,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x152, "BIT 2,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x153, "BIT 2,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x154, "BIT 2,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x155, "BIT 2,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x156, "BIT 2,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x157, "BIT 2,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x158, "BIT 3,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x159, "BIT 3,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x15A, "BIT 3,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x15B, "BIT 3,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x15C, "BIT 3,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x15D, "BIT 3,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x15E, "BIT 3,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x15F, "BIT 3,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x160, "BIT 4,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x161, "BIT 4,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x162, "BIT 4,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x163, "BIT 4,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x164, "BIT 4,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x165, "BIT 4,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x166, "BIT 4,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x167, "BIT 4,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x168, "BIT 5,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x169, "BIT 5,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x16A, "BIT 5,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x16B, "BIT 5,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x16C, "BIT 5,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x16D, "BIT 5,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x16E, "BIT 5,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x16F, "BIT 5,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x170, "BIT 6,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x171, "BIT 6,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x172, "BIT 6,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x173, "BIT 6,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x174, "BIT 6,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x175, "BIT 6,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x176, "BIT 6,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x177, "BIT 6,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x178, "BIT 7,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x179, "BIT 7,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x17A, "BIT 7,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x17B, "BIT 7,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x17C, "BIT 7,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x17D, "BIT 7,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x17E, "BIT 7,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x17F, "BIT 7,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x180, "RES 0,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x181, "RES 0,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x182, "RES 0,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x183, "RES 0,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x184, "RES 0,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x185, "RES 0,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x186, "RES 0,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x187, "RES 0,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x188, "RES 1,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x189, "RES 1,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x18A, "RES 1,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x18B, "RES 1,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x18C, "RES 1,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x18D, "RES 1,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x18E, "RES 1,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x18F, "RES 1,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x190, "RES 2,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x191, "RES 2,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x192, "RES 2,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x193, "RES 2,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x194, "RES 2,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x195, "RES 2,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x196, "RES 2,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x197, "RES 2,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x198, "RES 3,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x199, "RES 3,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x19A, "RES 3,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x19B, "RES 3,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x19C, "RES 3,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x19D, "RES 3,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x19E, "RES 3,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x19F, "RES 3,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A0, "RES 4,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A1, "RES 4,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A2, "RES 4,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A3, "RES 4,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A4, "RES 4,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A5, "RES 4,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A6, "RES 4,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A7, "RES 4,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A8, "RES 5,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1A9, "RES 5,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1AA, "RES 5,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1AB, "RES 5,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1AC, "RES 5,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1AD, "RES 5,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1AE, "RES 5,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1AF, "RES 5,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B0, "RES 6,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B1, "RES 6,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B2, "RES 6,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B3, "RES 6,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B4, "RES 6,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B5, "RES 6,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B6, "RES 6,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B7, "RES 6,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B8, "RES 7,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1B9, "RES 7,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1BA, "RES 7,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1BB, "RES 7,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1BC, "RES 7,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1BD, "RES 7,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1BE, "RES 7,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1BF, "RES 7,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C0, "SET 0,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C1, "SET 0,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C2, "SET 0,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C3, "SET 0,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C4, "SET 0,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C5, "SET 0,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C6, "SET 0,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C7, "SET 0,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C8, "SET 1,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1C9, "SET 1,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1CA, "SET 1,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1CB, "SET 1,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1CC, "SET 1,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1CD, "SET 1,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1CE, "SET 1,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1CF, "SET 1,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D0, "SET 2,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D1, "SET 2,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D2, "SET 2,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D3, "SET 2,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D4, "SET 2,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D5, "SET 2,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D6, "SET 2,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D7, "SET 2,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D8, "SET 3,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1D9, "SET 3,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1DA, "SET 3,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1DB, "SET 3,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1DC, "SET 3,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1DD, "SET 3,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1DE, "SET 3,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1DF, "SET 3,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E0, "SET 4,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E1, "SET 4,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E2, "SET 4,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E3, "SET 4,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E4, "SET 4,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E5, "SET 4,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E6, "SET 4,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E7, "SET 4,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E8, "SET 5,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1E9, "SET 5,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1EA, "SET 5,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1EB, "SET 5,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1EC, "SET 5,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1ED, "SET 5,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1EE, "SET 5,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1EF, "SET 5,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F0, "SET 6,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F1, "SET 6,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F2, "SET 6,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F3, "SET 6,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F4, "SET 6,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F5, "SET 6,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F6, "SET 6,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F7, "SET 6,A", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F8, "SET 7,B", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1F9, "SET 7,C", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1FA, "SET 7,D", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1FB, "SET 7,E", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1FC, "SET 7,H", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1FD, "SET 7,L", 1, 4, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1FE, "SET 7,(HL)", 1, 12, 0, InstructionKind::RSB8Bit),
        Instruction::new(0x1FF, "SET 7,A", 1, 4, 0, InstructionKind::RSB8Bit),
    ]
}
