[package]
name = "fpt"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
num-traits = "0.2"
rand = "0.8"
blip_buf = "0.1"

[dev-dependencies]
rstest = "0.18"

[build-dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
