name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'	
    - uses: Swatinem/rust-cache@v2
    - name: Fetch mooneye-test-suite
      run: >
        wget https://gekkio.fi/files/mooneye-test-suite/mts-20240127-1204-74ae166/mts-20240127-1204-74ae166.tar.xz;
        tar -xvf mts-20240127-1204-74ae166.tar.xz;
        mkdir -p third_party/mooneye-test-suite;
        mv mts-20240127-1204-74ae166 third_party/mooneye-test-suite/build;
    - name: Version
      run: rustc --version
    - name: Run rustfmt
      run: cargo fmt --check
    - name: Unit tests
      run: cargo test -- --nocapture
    - name : Clippy
      run: cargo clippy --all-features
