name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Version
      run: rustc --version
    - name: Build
      run: for i in $(awk '/members = \[/{flag=1; next} /\]/{flag=0} flag' Cargo.toml | tr -d '",'); do cd $i; cargo rustc -- -D warnings; cd -; done


  clippy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: Swatinem/rust-cache@v2
        - name : Clippy
          run: cargo clippy --all-features -- -D warnings


  format-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run rustfmt
          run: cargo fmt --check


  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Unit tests
      run: cargo test -- --nocapture
