name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Version
      run: rustc --version
    - name: Build
      run: cargo build --verbose


  clippy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: Swatinem/rust-cache@v2
        - name : Clippy
          run: cargo clippy --verbose --all-features


  format-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run rustfmt
          run: cargo fmt --check


  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Unit tests
      run: cargo test -- --nocapture
